---
title: "Fish Orders Gut Microniome Analysis"
output: html_document
---

```{r loading_packages}
library(tidyverse)
library(phyloseq)
library(vegan)
library(ggpubr)
library(microbiome)
library(indicspecies)
library(writexl)
library(ANCOMBC)
library(ggVennDiagram)
```

```{r loading_data}

# Loading Necessary Data to be Used
counts = read.delim("feature-table.txt", skip =1, row.names =1)
taxonomy = read.delim("taxonomy.tsv", row.names = 1)
metadata = read.delim("fish_metadata_cleaned.tsv")
tree = read_tree("tree.nwk")
```

```{r phloseq_object}

# filter the metadata to only the four orders and sample collected in rocky reef along with midgut&hindgut
metadata_filtered = metadata %>% filter(p_order %in% c("Perciformes","Centrarchiformes","Blenniiformes", "Labriformes"), substrata_collection %in% "rocky reef", sample_type %in% c("midgut","hindgut"))

# Rank the four order, which will make Perciformes as a control in DESeq Analysis
metadata_filtered$p_order = factor(metadata_filtered$p_order, levels = c("Perciformes", "Centrarchiformes", "Blenniiformes", "Labriformes"))

# Change X.SampleID column name
names(metadata_filtered)[names(metadata_filtered) == "X.SampleID"] <- "Sample"

# Remove counts dataframe's columns that are not in new filtered metadata
included_names = metadata_filtered[,1]
colnames_trimmed <- substr(colnames(counts), 2, nchar(colnames(counts)))
counts_filtered = counts[, colnames_trimmed %in% included_names]

# Make the first column of metadata_filtered to row names
rownames(metadata_filtered) <- metadata_filtered[[1]]
metadata_filtered <- metadata_filtered[,-1]

# Remove the first letter of all the columns to make sure it match the metadata's samples names
colnames(counts_filtered) <- substr(colnames(counts_filtered), 2, nchar(colnames(counts_filtered)))

# Taxonomy of bacteria formatting and cleaning
taxonomy_formatted = taxonomy %>% separate(col = Taxon, 
           into = c('Domain','Phylum','Class','Order',
                    'Family','Genus','Species'),
           sep=';', fill='right') %>% 
  select(-Confidence) %>% mutate(across(everything(), ~ trimws(as.character(.))))

# Due to some of the taxonomy on taxonomy dataframe show something like: o__, p__, or g__, they are removed
two_character_values_replacement <- function(taxonomy_formatted) {
  taxonomy_formatted[] <- lapply(taxonomy_formatted, function(col) {
    if (is.factor(col)) {
      col <- as.character(col)}
if (is.character(col)) {
      col[grepl("^[__A-Za-z]{3}$", col)] <- NA
    }
    return(col)
  })
  return(taxonomy_formatted)
}
taxonomy_formatted_fixed = two_character_values_replacement(taxonomy_formatted)

# Final steps to create phyloseq object
taxonomy_fromatted_matrix = as.matrix(taxonomy_formatted_fixed)
counts_formatted = counts_filtered %>% as.matrix()
ps = phyloseq(sample_data(metadata_filtered),
              otu_table(counts_formatted, taxa_are_rows = T),
              tax_table(taxonomy_fromatted_matrix),
              tree)

# Save phyloseq object
saveRDS(ps,'phyloseq_taxonomy.rds')

sample_data(ps)
```

```{r phyloseq_object_analysis}

# Analysis for the phyloseq object and defining the indicator species for the four orders
ps_order = tax_glom(ps,'Genus')

sample_data(ps_order)
ps_relab = transform(ps_order, 'compositional')
ps_filt = filter_taxa(ps_relab, function(x) mean(x) > 0.0001, TRUE)
otu_table = data.frame(otu_table(ps_filt))
set.seed(420)
indval = multipatt( t(otu_table), 
            cluster= ps_filt@sam_data$p_order,
          control = how(nperm = 999) )
summary(indval, indvalcomp = TRUE)
```

```{r Core_Microbiome}

psrare = rarefy_even_depth(ps, sample.size = 191)
ps_rare_relab = transform(psrare, 'compositional')
ps_rare_relab_order = tax_glom(ps_rare_relab, "Genus")

order.perciformes = subset_samples(ps_rare_relab_order, p_order == "Perciformes")
order.blenniiformes = subset_samples(ps_rare_relab_order, p_order == "Blenniiformes") 
order.labriformes = subset_samples(ps_rare_relab_order, p_order == "Labriformes")
order.centrarchiformes = subset_samples(ps_rare_relab_order, p_order == "Centrarchiformes")


sample_data(order.perciformes)

ASVs_performes = core_members(order.perciformes, detection=0.001, prevalence = 0.4)
ASVs_blenniiformes = core_members(order.blenniiformes, detection=0.001, prevalence = 0.4)
ASVs_labriformes = core_members(order.labriformes, detection=0.001, prevalence = 0.4)
ASVs_centrarchiformes = core_members(order.centrarchiformes, detection=0.001, prevalence = 0.4)

ASVs_centrarchiformes

ggVennDiagram(list(ASVs_performes, ASVs_blenniiformes, ASVs_labriformes, ASVs_centrarchiformes), set_size = 6, category.names = c("Perciformes","Blenniiformes", "Labriformes", "Centrarchiformes") )
```

```{r DESeq-analysis}

ps_Labriformes = subset_samples(ps, p_order == c("Perciformes","Labriformes"))
ps_Blenniiformes = subset_samples(ps, p_order == c("Perciformes", "Blenniiformes"))
ps_Centrarchiformes = subset_samples(ps, p_order == c("Perciformes","Centrarchiformes"))
  
  
set.seed(420)
Labriformes_deseq = ancombc2(ps_Labriformes, rank = taxonomic_level,
          fix_formula = "p_order",
          p_adj_method = "BH",
          prv_cut = 0.1)

Labriformes_table = Labriformes_deseq$res

Labriformes_deseq_T = Labriformes_table |> subset(diff_robust_p_orderLabriformes == TRUE)

Labriformes_deseq_T

Labriformes_table %>% subset(!is.na(lfc_p_orderLabriformes)) |>
  ggplot(aes(taxon,lfc_p_orderLabriformes)) +
  geom_col() +
  coord_flip() +
  ggtitle("Labriformes DESeq Result")

set.seed(420)
Blenniiformes_deseq = ancombc2(ps_Blenniiformes, rank = taxonomic_level,
          fix_formula = "p_order",
          p_adj_method = "BH",
          prv_cut = 0.1)

Blenniiformes_table = Blenniiformes_deseq$res

Blenniiformes_deseq_T = Blenniiformes_table |> subset(diff_robust_p_orderBlenniiformes == TRUE)

Blenniiformes_deseq_T

Blenniiformes_table %>% subset(!is.na(lfc_p_orderBlenniiformes)) |>
  ggplot(aes(taxon,lfc_p_orderBlenniiformes)) +
  geom_col() +
  coord_flip() +
  ggtitle("Blenniiformes DESeq Result")

set.seed(420)
Centrarchiformes_deseq = ancombc2(ps_Centrarchiformes, rank = taxonomic_level,
          fix_formula = "p_order",
          p_adj_method = "BH",
          prv_cut = 0.1)

Centrarchiformes_table = Centrarchiformes_deseq$res

Centrarchiformes_deseq_T = Centrarchiformes_table |> subset(diff_robust_p_orderCentrarchiformes == TRUE)

Centrarchiformes_deseq_T

Centrarchiformes_table %>% subset(!is.na(lfc_p_orderCentrarchiformes)) |>
  ggplot(aes(taxon,lfc_p_orderCentrarchiformes)) +
  geom_col() +
  coord_flip() +
   ggtitle("Centrarchiformes DESeq Result")


```
